/* 
 * webApiTask
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ToDoListApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ToDoListApiTests
    {
        private ToDoListApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ToDoListApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ToDoListApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ToDoListApi
            //Assert.IsInstanceOfType(typeof(ToDoListApi), instance, "instance is a ToDoListApi");
        }

        
        /// <summary>
        /// Test ToDoListDelete
        /// </summary>
        [Test]
        public void ToDoListDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ToDoListDelete(id);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ToDoListGet
        /// </summary>
        [Test]
        public void ToDoListGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ToDoListGet(id);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ToDoListGetAll
        /// </summary>
        [Test]
        public void ToDoListGetAllTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ToDoListGetAll();
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ToDoListPost
        /// </summary>
        [Test]
        public void ToDoListPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ToDoList toDoList = null;
            //var response = instance.ToDoListPost(toDoList);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
        /// <summary>
        /// Test ToDoListPut
        /// </summary>
        [Test]
        public void ToDoListPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ToDoList toDoList = null;
            //var response = instance.ToDoListPut(toDoList);
            //Assert.IsInstanceOf<Object> (response, "response is Object");
        }
        
    }

}
